trigger:
  branches:
    include:
      - main

pool:
  name: default

variables:
- group: backend-variables

steps:
- checkout: self

- task: Docker@2
  displayName: Build and push image to ACR
  inputs:
    command: buildAndPush
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    dockerfile: Dockerfile
    tags: |
      $(Build.BuildId)
      latest

# - script: |
#     set -e

#     git config --global user.email "azuredevops@local"
#     git config --global user.name "azure-pipeline"

#     git clone https://github.com/Sotatek-KhanhPhung/LAB-AKS-BE-gitops.git gitops
#     cd gitops

#     sed -i "s#image: .*#image: $(containerRegistry)/$(imageRepository):$(Build.BuildId)#" k8s/backend/deployment.yaml

#     git add k8s/backend/deployment.yaml
#     git commit -m "Update backend image to $(Build.BuildId)"
#     git -c http.extraHeader="Authorization: Bearer $(GITOPS_PAT)" push origin main
#   displayName: Update GitOps repo                     

- script: |
    set -e

    echo "Clone repo"
    git clone https://$(GITOPS_PAT)@github.com/Sotatek-KhanhPhung/LAB-AKS-BE-gitops.git
    cd LAB-AKS-BE-gitops

    git config user.email "azuredevops@local"
    git config user.name "azure-pipeline"

    echo "Set remote with PAT"
    git remote set-url origin https://$(GITOPS_PAT)@github.com/Sotatek-KhanhPhung/LAB-AKS-BE-gitops.git

    echo "Update image"
    sed -i "s|image:.*|image: $(containerRegistry)/$(imageRepository):$(Build.BuildId)|g" k8s/backend/deployment.yaml

    git add k8s/backend/deployment.yaml

    if git diff --cached --quiet; then
      echo "No changes to commit"
      exit 0
    fi

    git commit -m "Update backend image to $(Build.BuildId)"
    git push origin main
  displayName: Update GitOps repo