
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - app/*
      - app/**/*
      - server.js
      - package.json
      - package-lock.json
      - Dockerfile

pr:
  branches:
    include:
      - main

pool:
  name: default

variables:
  azureServiceConnection: 'service-connection-lab'
  dockerRegistryServiceConnection: 'service-connection-docker-registry'
  acrLoginServer: 'acrthreetierlab.azurecr.io'
  acrRepository: 'acrthreetierlab'
  webAppName: 'be-three-tier-as'
  resourceGroupName: 'three-tier-lab'
  imageTag: '$(Build.BuildId)'
  imageName: '$(acrLoginServer)/$(acrRepository):$(imageTag)'

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildPush
    pool:
      name: default
    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build and push image to ACR
      inputs:
        command: buildAndPush
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(acrRepository)'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(imageTag)
          latest

- stage: Deploy
  dependsOn: BuildAndPush
  jobs:
  - deployment: DeployToAppService
    pool:
      name: default
    environment: prod-backend
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy image to App Service
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appName: '$(webAppName)'
              containers: '$(imageName)'